 import testt
DREAMS package found at: /Users/anjali/Desktop/DREAMS
Starting observation test...
astar.bug_report - ERROR: Unhandled exception occured, see log file for details.
Traceback (most recent call last):
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scopesim/utils.py", line 726, in wrapper
    output = func(*args, **kwargs)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scopesim/optics/optical_train.py", line 209, in observe
    source = effect.apply_to(source)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scopesim/effects/ter_curves.py", line 116, in apply_to
    obj.spectra[isp] = combine_two_spectra(spec, thru, "multiply",
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scopesim/effects/ter_curves_utils.py", line 385, in combine_two_spectra
    spec_c = spec_a(wave) * spec_b(wave)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/synphot/spectrum.py", line 367, in __call__
    return self.model(w.value) * self._internal_flux_unit
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/astropy/modeling/core.py", line 418, in __call__
    new_call = make_function_with_signature(
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/astropy/modeling/core.py", line 395, in __call__
    return super(cls, self).__call__(*inputs, **kwargs)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/astropy/modeling/core.py", line 1125, in __call__
    outputs = self._generic_evaluate(evaluate, inputs, fill_value, with_bbox)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/astropy/modeling/core.py", line 1087, in _generic_evaluate
    outputs = evaluate(_inputs)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/astropy/modeling/core.py", line 975, in evaluate
    return self.evaluate(*chain(_inputs, parameters))
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/synphot/models.py", line 432, in evaluate
    y = super(Empirical1D, self).evaluate(inputs)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/astropy/modeling/tabular.py", line 242, in evaluate
    result = interpn(
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scipy/interpolate/_rgi.py", line 726, in interpn
    grid, descending_dimensions = _check_points(points)
  File "/Users/anjali/opt/anaconda3/lib/python3.9/site-packages/scipy/interpolate/_rgi.py", line 31, in _check_points
    raise ValueError(
ValueError: The points in dimension 0 must be strictly ascending or descending
astar.bug_report - ERROR: Python:
3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ]

